import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';

const root = process.cwd();
const publicDir = path.join(root, 'public');
const docsDir = path.join(root, 'docs');
const nodeModules = path.join(root, 'node_modules');

// Configuration
const repoName = process.argv[2] || ''; // Pass repo name as argument, e.g. "my-repo"
const baseUrl = repoName ? `/${repoName}/` : '/';

console.log(`Building static site for base URL: ${baseUrl}`);

// 1. Clean and create public dir
if (fs.existsSync(publicDir)) {
  fs.rmSync(publicDir, { recursive: true, force: true });
}
fs.mkdirSync(publicDir);

// 2. Build the workshop markdown (using existing script)
console.log('Generating workshop markdown...');
execSync('npm run docs:gen', { stdio: 'inherit' });

// 3. Copy MOAW website assets
const moawWebsiteDir = path.join(nodeModules, '@moaw/cli/dist/website');
if (!fs.existsSync(moawWebsiteDir)) {
  console.error('MOAW website assets not found using generated path detection. Trying standard path...');
  console.error(`Checked: ${moawWebsiteDir}`);
  process.exit(1);
}

console.log('Copying MOAW website assets...');
fs.cpSync(moawWebsiteDir, publicDir, { recursive: true });

// 4. Copy docs to public/workshops
// moaw serve maps the workshop directory to /workshops path
const workshopsDir = path.join(publicDir, 'workshops');
fs.mkdirSync(workshopsDir);
console.log('Copying workshop content...');
fs.cpSync(docsDir, workshopsDir, { recursive: true });

// 5. Patch index.html
const indexHtmlPath = path.join(publicDir, 'index.html');
let indexHtml = fs.readFileSync(indexHtmlPath, 'utf-8');

// Replace <base href="/"> with correct base
indexHtml = indexHtml.replace('<base href="/">', `<base href="${baseUrl}">`);

// Remove the hardcoded GitHub Pages script block that forces /moaw/ base
// This regex looks for the specific script tag content generated by MOAW
indexHtml = indexHtml.replace(
  /<script>\s*if \(window\.location\.hostname\.includes\('\.github\.io'\)\) \{[\s\S]*?\}[\s\S]*?<\/script>/,
  ''
);

// Add a redirect for the root path to the workshop
// If user lands on /, redirect to /workshop/workshop.md
const redirectScript = `
<script>
  (function() {
    const basePath = '${baseUrl}';
    const workshopFile = 'workshop/workshop.md'; // Default MOAW path structure
    // If we are at the root (normalized), redirect to the workshop
    if (window.location.pathname.replace(/\\/$/, '') === basePath.replace(/\\/$/, '')) {
      window.location.replace(basePath + workshopFile);
    }
  })();
</script>
`;
indexHtml = indexHtml.replace('</body>', `${redirectScript}</body>`);

fs.writeFileSync(indexHtmlPath, indexHtml);

// 6. Create 404.html (copy of index.html) for SPA routing
fs.copyFileSync(indexHtmlPath, path.join(publicDir, '404.html'));

console.log('Static build complete in ./public');
